/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/account/api/login": {
    post: operations["Account_Login"];
  };
  "/account/api/logout": {
    delete: operations["Account_Logout"];
  };
  "/account/api/account": {
    get: operations["Account_GetAccount"];
    patch: operations["Account_UpdateAccount"];
  };
  "/account/api/accounts": {
    get: operations["Account_GetAccounts"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    LoginResponse: {
      status: components["schemas"]["ResponseStatus"];
      token?: string | null;
    };
    /** @enum {string} */
    ResponseStatus: "Success" | "SetNewPassword";
    LoginForm: {
      login: string;
      password: string;
      newPassword?: string | null;
    };
    UserAccountResponse: {
      /** Format: int32 */
      id?: number;
      name?: string;
      lastName?: string | null;
      email?: string | null;
      avatarUrl?: string | null;
    };
    UpdateAccountForm: {
      firstName?: string | null;
      lastName?: string | null;
      email?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  Account_Login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginForm"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
    };
  };
  Account_Logout: {
    responses: {
      200: {
        content: {
          "application/octet-stream": string;
        };
      };
    };
  };
  Account_GetAccount: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserAccountResponse"];
        };
      };
    };
  };
  Account_UpdateAccount: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAccountForm"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserAccountResponse"];
        };
      };
    };
  };
  Account_GetAccounts: {
    parameters: {
      query?: {
        accountIds?: number[];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserAccountResponse"][];
        };
      };
    };
  };
}
